spring:
  data:
    mongodb:
      host: ${MONGODB_HOST:localhost:27017}
      auto-index-creation: true
      username: ${MONGODB_USERNAME}
      password: ${MONGODB_PASSWORD}
      database: ${MONGODB_DATABASE:itemsDEV}
      authentication-database: ${AUTH_DATABASE:admin}

