spring:
  data:
    mongodb:
      host: ${MONGODB_HOST:localhost:27017}
      auto-index-creation: true
      username: ${MONGODB_USERNAME:root}
      password: ${MONGODB_PASSWORD:LEEXbM7nLq}
      database: ${MONGODB_DATABASE:itemsDEV}
      authentication-database: ${AUTH_DATABASE:admin}

